export const PROMPTS = {
  chapterGeneration: (contextPack: string, chapterGoal: string) =>
    [
      contextPack,
      "",
      "请根据以上上下文包和大纲，撰写以下章节：",
      chapterGoal,
      "",
      "要求：",
      "1. 严格遵循大纲中的情节走向",
      "2. 保持人物性格和说话方式一致",
      "3. 不要泄露角色尚不知道的信息",
      "4. 注意伏笔的埋设和回收",
      "5. 章节结尾要有钩子，吸引读者继续阅读",
      "6. 字数控制在 3000-5000 字",
    ].join("\n"),

  chapterContinuation: (contextPack: string, lastParagraph: string) =>
    [
      contextPack,
      "",
      "上一段内容：",
      lastParagraph,
      "",
      "请续写以下内容，保持风格和节奏一致：",
    ].join("\n"),

  chapterRevision: (contextPack: string, originalContent: string, revisionNotes: string) =>
    [
      contextPack,
      "",
      "原始章节内容：",
      originalContent.slice(0, 6000),
      "",
      "修改要求：",
      revisionNotes,
      "",
      "请根据修改要求重写章节，保持其他部分不变：",
    ].join("\n"),

  consistencyCheck: (contextPack: string, chapterContent: string) =>
    [
      contextPack,
      "",
      "请检查以下章节的连贯性：",
      chapterContent.slice(0, 8000),
      "",
      "检查维度：",
      "1. 人设一致性",
      "2. 时间线准确性",
      "3. 伏笔状态",
      "4. 角色认知合理性",
      "5. 设定一致性",
    ].join("\n"),

  OUTLINE_METHODOLOGY_VOLUME: [
    "## 卷纲方法论",
    "",
    "### 八节点结构",
    "每卷必须标注以下四个关键节点：",
    "- 1/4 节点：第一个重要转折",
    "- 中点：本卷中点关键事件",
    "- 3/4 节点：推进至最终高潮的关键转折",
    "- 高潮节点：本卷最高潮",
    "",
    "### 章节定位分类",
    "每章需标注定位标签：开场 / 发展 / 铺垫 / 转折 / 高潮 / 收束",
    "",
    "### 情绪弧线设计原则",
    "采用W形折线：起点→下降→回升→再降→最终回升",
    "",
    "### 爽点节律公式",
    "每章需标注章节区间、爽点类型、具体内容和预期效果",
  ].join("\n"),

  OUTLINE_METHODOLOGY_CHAPTER: [
    "## 细纲方法论",
    "",
    "### 五段式结构",
    "每章细纲必须按五段组织：起因 → 发展 → 转折 → 高潮 → 结尾",
    "",
    "### 多线安排",
    "需标注主线推进、辅线推进、事件线/任务线、感情线/关系线、逻辑线",
    "",
    "### 情节点功能标签",
    "每个情节点需标注功能标签和代价/收益兑现",
    "",
    "### 情绪变化标注",
    "标注起点→终点情绪变化路径",
    "",
    "### 钩子类型",
    "章首钩子类型：悬念对话开局 / 闪前碎片 / 倒计时开局 / 神秘独白 / 反差场景 / 未完成动作开局 / 意象预示",
    "章尾钩子类型：突然揭示 / 紧急危机 / 未完成动作 / 身份反转 / 两难抉择 / 神秘物品/线索 / 倒计时 / 承诺/威胁 / 离奇消失 / 隐藏含义 / 意象钩子 / 回声钩子 / 留白钩子",
  ].join("\n"),

  TRACKING_AWARENESS: [
    "## 伏笔与状态追踪要求",
    "",
    "1. 伏笔管理：明确标注伏笔的埋设、推进和回收节点，避免伏笔悬空",
    "2. 角色状态变化：角色能力、认知、关系、位置的变化必须可追踪，前后一致",
    "3. 信息差管理：不同角色之间的信息差必须明确标注，并控制信息释放节奏",
  ].join("\n"),

  WRITING_STYLE_TEMPLATE: [
    "## 文风设定",
    "",
    "以下为作品的文风偏好设定，请在撰写时严格遵循：",
    "",
    "### 句式偏好",
    "{sentencePreference}",
    "",
    "### 用词习惯",
    "{wordHabits}",
    "",
    "### 对话风格",
    "{dialogueStyle}",
    "",
    "### 节奏特点",
    "{rhythmFeatures}",
    "",
    "### 禁忌表达",
    "{tabooExpressions}",
  ].join("\n"),

  outlineGeneration: (genre: string, scale: string, premise: string, context: string) =>
    [
      "你是一位专业的小说大纲设计师。",
      "",
      `## 小说类型：${genre}`,
      `## 故事规模：${scale}`,
      `## 核心设定：${premise}`,
      "",
      "## 已有项目资料",
      context,
      "",
      "## 任务要求",
      "请根据以上信息，设计一个完整、有吸引力的小说大纲，包括：",
      "1. 核心故事概念与主题",
      "2. 主要人物设定（主角、重要配角、反派）",
      "3. 故事世界观与背景设定",
      "4. 整体故事结构（分卷/分篇规划）",
      "5. 关键情节节点与转折点",
      "6. 主要伏笔与悬念线",
      "",
      "请使用 Markdown 格式输出，保持结构清晰、层次分明。",
    ].join("\n"),
} as const
